'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SetupD2mod.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #cancmsg#.
        '''</summary>
        Friend ReadOnly Property CancelMsgKeyword() As String
            Get
                Return ResourceManager.GetString("CancelMsgKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #no#.
        '''</summary>
        Friend ReadOnly Property CancelMsgKeywordNo() As String
            Get
                Return ResourceManager.GetString("CancelMsgKeywordNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #yes#.
        '''</summary>
        Friend ReadOnly Property CancelMsgKeywordYes() As String
            Get
                Return ResourceManager.GetString("CancelMsgKeywordYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #completed#.
        '''</summary>
        Friend ReadOnly Property completed() As String
            Get
                Return ResourceManager.GetString("completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyfiles#.
        '''</summary>
        Friend ReadOnly Property copyFiles() As String
            Get
                Return ResourceManager.GetString("copyFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyfileserr#.
        '''</summary>
        Friend ReadOnly Property copyFilesErr() As String
            Get
                Return ResourceManager.GetString("copyFilesErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyfilesok#.
        '''</summary>
        Friend ReadOnly Property copyFilesOk() As String
            Get
                Return ResourceManager.GetString("copyFilesOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyglwrapper#.
        '''</summary>
        Friend ReadOnly Property copyGLWrapper() As String
            Get
                Return ResourceManager.GetString("copyGLWrapper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyglwrappererr#.
        '''</summary>
        Friend ReadOnly Property copyGLWrapperErr() As String
            Get
                Return ResourceManager.GetString("copyGLWrapperErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyglwrapperok#.
        '''</summary>
        Friend ReadOnly Property copyGLWrapperOk() As String
            Get
                Return ResourceManager.GetString("copyGLWrapperOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyslang#.
        '''</summary>
        Friend ReadOnly Property copySoundLang() As String
            Get
                Return ResourceManager.GetString("copySoundLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyslangerr#.
        '''</summary>
        Friend ReadOnly Property copySoundLangErr() As String
            Get
                Return ResourceManager.GetString("copySoundLangErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copyslangok#.
        '''</summary>
        Friend ReadOnly Property copySoundLangOk() As String
            Get
                Return ResourceManager.GetString("copySoundLangOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copytlang#.
        '''</summary>
        Friend ReadOnly Property copyTextLang() As String
            Get
                Return ResourceManager.GetString("copyTextLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copytlangerr#.
        '''</summary>
        Friend ReadOnly Property copyTextLangErr() As String
            Get
                Return ResourceManager.GetString("copyTextLangErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copytlangok#.
        '''</summary>
        Friend ReadOnly Property copyTextLangOk() As String
            Get
                Return ResourceManager.GetString("copyTextLangOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copytools#.
        '''</summary>
        Friend ReadOnly Property copyTools() As String
            Get
                Return ResourceManager.GetString("copyTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copytoolserr#.
        '''</summary>
        Friend ReadOnly Property copyToolsErr() As String
            Get
                Return ResourceManager.GetString("copyToolsErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #copytoolsok#.
        '''</summary>
        Friend ReadOnly Property copyToolsOk() As String
            Get
                Return ResourceManager.GetString("copyToolsOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .\Eng.
        '''</summary>
        Friend ReadOnly Property engFilesDir() As String
            Get
                Return ResourceManager.GetString("engFilesDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ##cancmsg#
        '''Abort installation?
        '''##yes#
        '''Yes
        '''##no#
        '''No
        '''#InstallModeLabel
        '''Choose installation mode
        '''#TextLangLabel
        '''Select interface text language
        '''#SoundLangLabel
        '''Select the language for unit voice on the global map
        '''#InstallRadioButton
        '''Install full and patched game
        '''#PatchRadioButton
        '''Patch my game (GOG, Russobit-M or Akella)
        '''#LangRuRadioButton
        '''Рус
        '''#LangEnRadioButton
        '''Eng
        '''#NextButton
        '''Next
        '''#BackButton
        '''Back
        '''#CancButton
        '''Cancel
        '''#SelectButton
        '''Select a folder
        '''#InfoLabel
        '''Select a folder to insta [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EngLang() As String
            Get
                Return ResourceManager.GetString("EngLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *** .
        '''</summary>
        Friend ReadOnly Property errorMsgTag() As String
            Get
                Return ResourceManager.GetString("errorMsgTag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .extracted.
        '''</summary>
        Friend ReadOnly Property extractedTmpFolder() As String
            Get
                Return ResourceManager.GetString("extractedTmpFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Briefing:Campaign:Exports:Globals:ImgData:Imgs:Interf:Links:manual:Music:MusicP:SaveGame:ScenData:Scens:Sounds:SoundsP:Video.
        '''</summary>
        Friend ReadOnly Property foldersList() As String
            Get
                Return ResourceManager.GetString("foldersList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .\Game.
        '''</summary>
        Friend ReadOnly Property gameDir() As String
            Get
                Return ResourceManager.GetString("gameDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Links#SaveGame#ScreenShots#Discipl2.exe.crash.txt.
        '''</summary>
        Friend ReadOnly Property IgnoreIOItem() As String
            Get
                Return ResourceManager.GetString("IgnoreIOItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #limitremoveerror#.
        '''</summary>
        Friend ReadOnly Property limitRemoveErr() As String
            Get
                Return ResourceManager.GetString("limitRemoveErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #limitremoveok#.
        '''</summary>
        Friend ReadOnly Property limitRemoveOk() As String
            Get
                Return ResourceManager.GetString("limitRemoveOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://norvezskayasemga.wixsite.com/d2bfwmod.
        '''</summary>
        Friend ReadOnly Property modSiteLink() As String
            Get
                Return ResourceManager.GetString("modSiteLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #nofileserror#.
        '''</summary>
        Friend ReadOnly Property noFilesFound() As String
            Get
                Return ResourceManager.GetString("noFilesFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #noglwrapperlinks#.
        '''</summary>
        Friend ReadOnly Property noGLWrapperLinks() As String
            Get
                Return ResourceManager.GetString("noGLWrapperLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #noslangerror#.
        '''</summary>
        Friend ReadOnly Property noSoundLangFound() As String
            Get
                Return ResourceManager.GetString("noSoundLangFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #notlangerror#.
        '''</summary>
        Friend ReadOnly Property noTextLangFound() As String
            Get
                Return ResourceManager.GetString("noTextLangFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #notoolserror#.
        '''</summary>
        Friend ReadOnly Property noToolsFound() As String
            Get
                Return ResourceManager.GetString("noToolsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #nowrappererror#.
        '''</summary>
        Friend ReadOnly Property noWrapperFound() As String
            Get
                Return ResourceManager.GetString("noWrapperFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .\Readme.
        '''</summary>
        Friend ReadOnly Property readmeDir() As String
            Get
                Return ResourceManager.GetString("readmeDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Software\norvezskayasemgaD2mod.
        '''</summary>
        Friend ReadOnly Property regKey() As String
            Get
                Return ResourceManager.GetString("regKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ##cancmsg#
        '''Прекратить установку?
        '''##yes#
        '''Да
        '''##no#
        '''Нет
        '''#InstallModeLabel
        '''Выберите режим установки
        '''#TextLangLabel
        '''Выберите язык интерфейса в игре
        '''#SoundLangLabel
        '''Выберите язык озвучки юнитов на глобальной карте
        '''#InstallRadioButton
        '''Установить полную и пропатченную версию игры
        '''#PatchRadioButton
        '''Пропатчить мою игру (GOG, Руссобит-М или Акелла)
        '''#LangRuRadioButton
        '''Рус
        '''#LangEnRadioButton
        '''Eng
        '''#NextButton
        '''Далее
        '''#BackButton
        '''Назад
        '''#CancButton
        '''Отмена
        '''#SelectButton
        '''Выберите папку
        '''#InfoLabel
        '''Вы [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RusLang() As String
            Get
                Return ResourceManager.GetString("RusLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.youtube.com/watch?v=XEFrECQ8yH4.
        '''</summary>
        Friend ReadOnly Property startGuideLink() As String
            Get
                Return ResourceManager.GetString("startGuideLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mod by Norvezskaya Semga v. .
        '''</summary>
        Friend ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .\Tools.
        '''</summary>
        Friend ReadOnly Property toolsDir() As String
            Get
                Return ResourceManager.GetString("toolsDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://verokster.blogspot.com/2019/03/disciples-i-ii-gl-wrapper-patch.html.
        '''</summary>
        Friend ReadOnly Property VerokBlog() As String
            Get
                Return ResourceManager.GetString("VerokBlog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .\Readme\Rus\patchlog.
        '''</summary>
        Friend ReadOnly Property versionPath1() As String
            Get
                Return ResourceManager.GetString("versionPath1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .\Readme\Eng\patchlog.
        '''</summary>
        Friend ReadOnly Property versionPath2() As String
            Get
                Return ResourceManager.GetString("versionPath2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
