'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SetupD2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #cancmsg#.
        '''</summary>
        Friend ReadOnly Property CancelMsgKeyword() As String
            Get
                Return ResourceManager.GetString("CancelMsgKeyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #no#.
        '''</summary>
        Friend ReadOnly Property CancelMsgKeywordNo() As String
            Get
                Return ResourceManager.GetString("CancelMsgKeywordNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #yes#.
        '''</summary>
        Friend ReadOnly Property CancelMsgKeywordYes() As String
            Get
                Return ResourceManager.GetString("CancelMsgKeywordYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ##cancmsg#
        '''Abort installation?
        '''##yes#
        '''Yes
        '''##no#
        '''No
        '''#InstallModeLabel
        '''Choose installation mode
        '''#TextLangLabel
        '''Select interface text language
        '''#SoundLangLabel
        '''Select the language for unit voice on the global map
        '''#InstallRadioButton
        '''Install full and patched game
        '''#PatchRadioButton
        '''Patch my game (GOG, Russobit-M or Akella)
        '''#LangRuRadioButton
        '''Рус
        '''#LangEnRadioButton
        '''Eng
        '''#NextButton
        '''Next
        '''#BackButton
        '''Back
        '''#CancButton
        '''Cancel
        '''#SelectButton
        '''Select a folder
        '''#InfoLabel
        '''Select a folder to install an already patched game
        '''or [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EngLang() As String
            Get
                Return ResourceManager.GetString("EngLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://norvezskayasemga.wixsite.com/d2bfwmod.
        '''</summary>
        Friend ReadOnly Property modSiteLink() As String
            Get
                Return ResourceManager.GetString("modSiteLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Software\norvezskayasemgaD2mod.
        '''</summary>
        Friend ReadOnly Property regKey() As String
            Get
                Return ResourceManager.GetString("regKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ##cancmsg#
        '''Прекратить установку?
        '''##yes#
        '''Да
        '''##no#
        '''Нет
        '''#InstallModeLabel
        '''Выберите режим установки
        '''#TextLangLabel
        '''Выберете язык интерфейса в игре
        '''#SoundLangLabel
        '''Выберете язык озвучки юнитов на глобальной карте
        '''#InstallRadioButton
        '''Установить полную и пропатченную версию игры
        '''#PatchRadioButton
        '''Пропатчить мою игру (GOG, Руссобит-М или Акелла)
        '''#LangRuRadioButton
        '''Рус
        '''#LangEnRadioButton
        '''Eng
        '''#NextButton
        '''Далее
        '''#BackButton
        '''Назад
        '''#CancButton
        '''Отмена
        '''#SelectButton
        '''Выберите папку
        '''#InfoLabel
        '''Выберите папку для установки уж [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RusLang() As String
            Get
                Return ResourceManager.GetString("RusLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.youtube.com/watch?v=XEFrECQ8yH4.
        '''</summary>
        Friend ReadOnly Property startGuideLink() As String
            Get
                Return ResourceManager.GetString("startGuideLink", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
